// Minimal consonant dataset (character, traditional name (Thai), romanized name, initial sound, final sound)
// You can regenerate this from the Python source if it changes.
const CONSONANTS = [
  ["ก","กอ ไก่","ko kai","g (voiced) initially","/k/ final"],
  ["จ","จอ จาน","cho jaan","j (affricate) initially","/t/ final"],
  ["ฎ","ฎอ ชฎา","do chada","d initially (rare)","/t/ final (rare)"],
  ["ฏ","ฏอ ปฏัก","to patak","t initially (rare)","/t/ final (rare)"],
  ["ด","ดอ เด็ก","do dek","d initially","/t/ final"],
  ["ต","ตอ เต่า","to tao","t initially","/t/ final"],
  ["บ","บอ ใบไม้","bo baimai","b initially","/p/ final"],
  ["ป","ปอ ปลา","po pla","p initially","/p/ final"],
  ["อ","ออ อ่าง","o aang","glottal stop carrier","—"],
  ["ข","ขอ ไข่","kho khai","kh aspirated","—"],
  ["ฃ","ฃอ ขวด","kho khuat","obsolete","—"],
  ["ฉ","ฉอ ฉิ่ง","cho ching","ch aspirated","—"],
  ["ฐ","ฐอ ฐาน","tho than","th aspirated","—"],
  ["ถ","ถอ ถุง","tho thung","th aspirated","—"],
  ["ผ","ผอ ผึ้ง","pho phueng","ph aspirated","—"],
  ["ฝ","ฝอ ฝา","fo fa","f","—"],
  ["ศ","ศอ ศาลา","so sala","s","/t/ final"],
  ["ษ","ษอ ฤาษี","so ruesi","s","/t/ final"],
  ["ส","สอ เสือ","so seua","s","/t/ final"],
  ["ห","หอ หีบ","ho hip","h; also silent carrier","—"],
  ["ค","คอ ควาย","kho khwaai","kh aspirated","/k/ final"],
  ["ฅ","ฅอ คน","kho khon","obsolete","—"],
  ["ฆ","ฆอ ระฆัง","kho rakhang","kh","/k/ final (rare)"],
  ["ง","งอ งู","ngo ngoo","ng","/ŋ/ final"],
  ["ช","ชอ ช้าง","cho chaang","ch","/t/ final (loans)"],
  ["ซ","ซอ โซ่","so soo","s","/t/ final"],
  ["ฌ","ฌอ เฌอ","cho choe","ch (rare)","—"],
  ["ญ","ญอ หญิง","yo ying","y (palatal)","/n/ final (Skt/Pali)"],
  ["ฑ","ฑอ มณโฑ","tho montho","th (rare)","/t/ final (rare)"],
  ["ฒ","ฒอ ผู้เฒ่า","tho phuthao","th (rare)","/t/ final (rare)"],
  ["ณ","ณอ เณร","no nen","n (retroflex)","/n/ final (formal)"],
  ["ท","ทอ ทหาร","tho thahan","th","/t/ final (Skt loans)"],
  ["ธ","ธอ ธง","tho thong","th","/t/ final (loans)"],
  ["น","นอ หนู","no nuu","n","/n/ final"],
  ["พ","พอ พาน","pho phan","ph","/p/ final (loans)"],
  ["ฟ","ฟอ ฟัน","fo fan","f","/p/ final (loans)"],
  ["ภ","ภอ สำเภา","pho samphao","ph","/p/ final (rare)"],
  ["ม","มอ ม้า","mo maa","m","/m/ final"],
  ["ย","ยอ ยักษ์","yo yak","y","/j/ glide final"],
  ["ร","รอ เรือ","ro ruea","r (often flapped)","/n/ final (spelled ร)"],
  ["ล","ลอ ลิง","lo ling","l","/n/ final (spelled ล)"],
  ["ว","วอ แหวน","wo waen","w","/w/ glide final"],
  ["ฬ","ฬอ จุฬา","lo chula","l (rare)","/n/ final (rare)"],
  ["ฮ","ฮอ นกฮูก","ho nokhuk","h","—"],
];
